export enum CellComponent {
  ArrayCell = 'ArrayCell',
  ArrayEditableCell = 'ArrayEditableCell',
  ArrayLookupCell = 'ArrayLookupCell',
  ArrayTagsCell = 'ArrayTagsCell',
  ArticleAdditionalInfoCell = 'ArticleAdditionalInfoCell',
  ArticleLinkInfoCell = 'ArticleLinkInfoCell',
  ArticleTypeCell = 'ArticleTypeCell',
  DateCell = 'DateCell',
  EditedDateCell = 'EditedDateCell',
  EditImageGalleryCell = 'EditImageGalleryCell',
  EditRoomBookedCell = 'EditRoomBookedCell',
  EditRoomVenueCell = 'EditRoomVenueCell',
  EventDocumentCell = 'EventDocumentCell',
  GpsPointsCell = 'GpsPointsCell',
  HtmlCell = 'HtmlCell',
  InputReferenceCell = 'InputReferenceCell',
  ImageCell = 'ImageCell',
  ImageEditCell = 'ImageEditCell',
  ImageGalleryCell = 'ImageGalleryCell',
  JsonCell = 'JsonCell',
  LoadingCell = 'LoadingCell',
  OperationScheduleCell = 'OperationScheduleCell',
  SelectWithOptionsCell = 'SelectWithOptionsCell',
  StateCell = 'StateCell',
  StringCell = 'StringCell',
  TagCell = 'TagCell',
  TagReferenceCell = 'TagReferenceCell',
  UrlCell = 'UrlCell',
  StringTemplateCell = 'StringTemplateCell',
  TextAreaCell = 'TextAreaCell',
  TextHighlightCell = 'TextHighlightCell',
  ToggleCell = 'ToggleCell',
  ToggleButtonCell = 'ToggleButtonCell',
  TypeBasedCell = 'TypeBasedCell',
  WebcamCell = 'WebcamCell',
  WebcamGalleryCell = 'WebcamGalleryCell',

  QuickViewTextInfoCard = 'QuickViewTextInfoCard',
  QuickViewContactsCard = 'QuickViewContactsCard',
  QuickViewWebcamsView = 'QuickViewWebcamsView',
  QuickViewMapView = 'QuickViewMapView',
  QuickViewOpeningHoursView = 'QuickViewOpeningHoursView',
  QuickViewRecordInfoView = 'QuickViewRecordInfoView',
}

export enum FilterComponent {
  FixedValue = 'FixedValue',
}
