export enum CellComponent {
  ArrayCell = 'ArrayCell',
  DateCell = 'DateCell',
  EditedDateCell = 'EditedDateCell',
  GpsGalleryCell = 'GpsGalleryCell',
  HtmlCell = 'HtmlCell',
  ImageCell = 'ImageCell',
  ImageGalleryCell = 'ImageGalleryCell',
  JsonCell = 'JsonCell',
  StateCell = 'StateCell',
  StringCell = 'StringCell',
  StringTemplateCell = 'StringTemplateCell',
  TextHighlightCell = 'TextHighlightCell',
  WebcamGalleryCell = 'WebcamGalleryCell',
}
