export enum CellComponent {
  ArrayCell = 'ArrayCell',
  ArrayCellTags = 'ArrayCellTags',
  ArticleAdditionalInfoCell = 'ArticleAdditionalInfoCell',
  ArticleLinkInfoCell = 'ArticleLinkInfoCell',
  ArticleTypeCell = 'ArticleTypeCell',
  DateCell = 'DateCell',
  EditedDateCell = 'EditedDateCell',
  EditImageGalleryCell = 'EditImageGalleryCell',
  EditRoomBookedCell = 'EditRoomBookedCell',
  GpsPointsCell = 'GpsPointsCell',
  HtmlCell = 'HtmlCell',
  InputReferenceCell = 'InputReferenceCell',
  ImageCell = 'ImageCell',
  ImageEditCell = 'ImageEditCell',
  ImageGalleryCell = 'ImageGalleryCell',
  JsonCell = 'JsonCell',
  OdhTagCell = 'OdhTagCell',
  SelectWithOptionsCell = 'SelectWithOptionsCell',
  StateCell = 'StateCell',
  StringCell = 'StringCell',
  TagCell = 'TagCell',
  UrlCell = 'UrlCell',
  StringTemplateCell = 'StringTemplateCell',
  TextAreaCell = 'TextAreaCell',
  TextHighlightCell = 'TextHighlightCell',
  ToggleCell = 'ToggleCell',
  TypeBasedCell = 'TypeBasedCell',
  WebcamCell = 'WebcamCell',
}

export enum FilterComponent {
  FixedValue = 'FixedValue',
}
