import { html, TemplateResult } from 'lit-html';
import '../../databrowser-odhActivityPoi';

export default {
  title: 'OdhActivityPoiDetail',
  component: 'databrowser-odh-activity-poi-detail',
  argTypes: {
    data: { control: 'object' },
  },
};

interface Story<T> {
  (args: T): TemplateResult;
  args?: Partial<T>;
  argTypes?: Record<string, unknown>;
}

interface ArgTypes {
  data?: any;
}

const Template: Story<ArgTypes> = ({ data = {} }: ArgTypes) => html`
  <databrowser-odh-activity-poi-detail
    .data="${data}"
  ></databrowser-odh-activity-poi-detail>
`;

export const Regular = Template.bind({});
Regular.args = {
  data: {
    Id: 'smgpoic6f1f5c5b3b39d66a0ef80e5bece94a4',
    Self: 'https://api.tourism.testingmachine.eu/v1/ODHActivityPoi/smgpoic6f1f5c5b3b39d66a0ef80e5bece94a4',
    Type: 'Kultur Sehenswürdigkeiten',
    AgeTo: 0,
    Areas: [
      {
        Id: '3037440EA25C4E369CEDA7C5F09B6303',
        Self: 'https://api.tourism.testingmachine.eu/v1/Area/3037440EA25C4E369CEDA7C5F09B6303',
      },
    ],
    SmgId: '',
    _Meta: {
      Id: 'smgpoic6f1f5c5b3b39d66a0ef80e5bece94a4',
      Type: 'odhactivitypoi',
      Source: 'lts',
      LastUpdate: '2021-03-10T23:12:08.4130174',
    },
    Active: true,
    AreaId: ['3037440EA25C4E369CEDA7C5F09B6303'],
    Detail: {
      de: {
        Title: '11 Der Nittbach',
        Header: '',
        BaseText:
          '<p><strong>N i t t &ndash; B a c h &ndash; W a s s e r </strong></p>\r\n<p>&nbsp;</p>\r\n<p><strong>Der Nittbach</strong> selbst, entspringt nicht aus einer eigenen Quelle, sondern bildet sich aus mehreren Rinnsalen, die auf Prader Gemeindegebiet bereits oberhalb der Kalblh&uuml;tte auf ca. 2150 m ihre Urspr&uuml;nge aufweisen. Die Wasser des Nittbaches waren nicht nur f&uuml;r die Prader Flur-Riede, den Nitt-, Standlair- und Tschesswiesen von besonderer Wichtigkeit, sondern sie dienten auch als Trink- und Bew&auml;sserungswasser f&uuml;r den Standlairhof und Teilen des Alt Tschenglser Feldes. Von den Besitzern des Letzteren, war der &bdquo;Gemeinde-Ausrufer&ldquo; von Prad, laut &bdquo;Nittbach-Wasservertrag vom 22. Mai 1510, dazu berechtigt, allj&auml;hrlich am 24. Mai um 13 Uhr am Kirchplatz von Tschengls einen Wasserzins, in Form von Getreide, einzufordern. Zudem legte genanntes Vertragswerk auch ein genaues Wasserbezugsrecht fest. Dessen zugemessene Menge richtete sich nach dem Wasservorkommen und kam allj&auml;hrlich am Mitte Mai-Abend durch die Dorfmeister von Prad und Tschengls an Ort und Stelle zur genauen Aufteilung. Die Wasserzuteilung an die jeweiligen Grundbesitzer nahm hingegen der j&auml;hrlich neu bestellte &bdquo;Waaler&ldquo; vor. Er teilte dem an die Reihe Kommenden den Beginn und die Dauer der Bew&auml;sserungszeit mit. Im Herbst, am Ende der Bew&auml;sserungsperiode, zog der &bdquo;Wasseransager&ldquo; mit Hand-Ziehkarren und Getreidema&szlig; von einem Wasser-Nutznie&szlig;er zum anderen. Denn bei jedem hatte er f&uuml;r seine M&uuml;he, je nach &bdquo;W&auml;sserungsstunden&ldquo;, eine bestimmte Getreidemenge in Empfang zu nehmen. Nach dem Bau der Beregnungs-Anlagen ab den 1970er-Jahren kam dieser alt hergebrachte Brauch zum Erliegen. Der nunmehr so genannte Beregnungswart l&ouml;ste den &bdquo;Waalerdienst&ldquo; ab.</p>\r\n<p><strong>Das &bdquo;Nittbach-Wasser&ldquo;</strong> versorgte stets nicht allein Mensch, Tier und Flur mit seinem kostbaren Nass, sondern es barg in sich dar&uuml;ber hinaus auch noch eine heilende Wirkung. So ist uns &uuml;berliefert, dass fu&szlig;leidende Menschen und Haustiere nach einem Bad in &bdquo;Nittwasser&ldquo; geheilt wurden. Dies bewog gar Einige die eigentliche Quelle zu finden, allein dies gelang aus oben erw&auml;hnten Gr&uuml;nden nicht. In den ersten 1990er-Jahren hat man schlie&szlig;lich unweit des &bdquo;Nittkreuzes&ldquo;, in direkter Weg N&auml;he, eine Art Wassertretanlage errichtet, die seither von G&auml;sten und Einheimischen sehr gerne in Anspruch genommen wird.</p>\r\n<p>Durch das Wassertreten wird der&nbsp;<a href="http://de.wikipedia.org/wiki/Blutkreislauf">Kreislauf</a>&nbsp;angeregt und die arterielle&nbsp;<a href="http://de.wikipedia.org/wiki/Durchblutung">Durchblutung</a>&nbsp;gef&ouml;rdert. Der K&auml;ltereiz l&auml;sst die oberfl&auml;chlichen Blutgef&auml;&szlig;e kontrahieren. Gemeinsam mit der Muskelbewegung f&ouml;rdert dies auch den ven&ouml;sen Blutstrom und beugt&nbsp;<a href="http://de.wikipedia.org/wiki/Krampfader">Krampfadern</a>&nbsp;vor. Abends durchgef&uuml;hrt ist Wassertreten &uuml;brigens eine Hilfestellung zum besseren Einschlafen.</p>',
        Keywords: null,
        Language: 'de',
        MetaDesc:
          'Ein "Must See" in Südtirol: 11 Der Nittbach. Alle Informationen zum sehenswerten Platz. • Anfahrt • Wegbeschreibung • Kontakt • und vieles mehr. ',
        AuthorTip: null,
        IntroText: '',
        MetaTitle: '11 Der Nittbach • Südtirol Highlights',
        SubHeader: null,
        SafetyInfo: null,
        ParkingInfo: null,
        GetThereText: null,
        EquipmentInfo: null,
        AdditionalText: '',
        PublicTransportationInfo: null,
      },
      en: {
        Title: '11 Der Nittbach',
        Header: '',
        BaseText:
          '<p><strong>N i t t &ndash; B a c h &ndash; W a s s e r </strong></p>\r\n<p>&nbsp;</p>\r\n<p><strong>Der Nittbach</strong> selbst, entspringt nicht aus einer eigenen Quelle, sondern bildet sich aus mehreren Rinnsalen, die auf Prader Gemeindegebiet bereits oberhalb der Kalblh&uuml;tte auf ca. 2150 m ihre Urspr&uuml;nge aufweisen. Die Wasser des Nittbaches waren nicht nur f&uuml;r die Prader Flur-Riede, den Nitt-, Standlair- und Tschesswiesen von besonderer Wichtigkeit, sondern sie dienten auch als Trink- und Bew&auml;sserungswasser f&uuml;r den Standlairhof und Teilen des Alt Tschenglser Feldes. Von den Besitzern des Letzteren, war der &bdquo;Gemeinde-Ausrufer&ldquo; von Prad, laut &bdquo;Nittbach-Wasservertrag vom 22. Mai 1510, dazu berechtigt, allj&auml;hrlich am 24. Mai um 13 Uhr am Kirchplatz von Tschengls einen Wasserzins, in Form von Getreide, einzufordern. Zudem legte genanntes Vertragswerk auch ein genaues Wasserbezugsrecht fest. Dessen zugemessene Menge richtete sich nach dem Wasservorkommen und kam allj&auml;hrlich am Mitte Mai-Abend durch die Dorfmeister von Prad und Tschengls an Ort und Stelle zur genauen Aufteilung. Die Wasserzuteilung an die jeweiligen Grundbesitzer nahm hingegen der j&auml;hrlich neu bestellte &bdquo;Waaler&ldquo; vor. Er teilte dem an die Reihe Kommenden den Beginn und die Dauer der Bew&auml;sserungszeit mit. Im Herbst, am Ende der Bew&auml;sserungsperiode, zog der &bdquo;Wasseransager&ldquo; mit Hand-Ziehkarren und Getreidema&szlig; von einem Wasser-Nutznie&szlig;er zum anderen. Denn bei jedem hatte er f&uuml;r seine M&uuml;he, je nach &bdquo;W&auml;sserungsstunden&ldquo;, eine bestimmte Getreidemenge in Empfang zu nehmen. Nach dem Bau der Beregnungs-Anlagen ab den 1970er-Jahren kam dieser alt hergebrachte Brauch zum Erliegen. Der nunmehr so genannte Beregnungswart l&ouml;ste den &bdquo;Waalerdienst&ldquo; ab.</p>\r\n<p><strong>Das &bdquo;Nittbach-Wasser&ldquo;</strong> versorgte stets nicht allein Mensch, Tier und Flur mit seinem kostbaren Nass, sondern es barg in sich dar&uuml;ber hinaus auch noch eine heilende Wirkung. So ist uns &uuml;berliefert, dass fu&szlig;leidende Menschen und Haustiere nach einem Bad in &bdquo;Nittwasser&ldquo; geheilt wurden. Dies bewog gar Einige die eigentliche Quelle zu finden, allein dies gelang aus oben erw&auml;hnten Gr&uuml;nden nicht. In den ersten 1990er-Jahren hat man schlie&szlig;lich unweit des &bdquo;Nittkreuzes&ldquo;, in direkter Weg N&auml;he, eine Art Wassertretanlage errichtet, die seither von G&auml;sten und Einheimischen sehr gerne in Anspruch genommen wird.</p>\r\n<p>Durch das Wassertreten wird der&nbsp;<a href="http://de.wikipedia.org/wiki/Blutkreislauf">Kreislauf</a>&nbsp;angeregt und die arterielle&nbsp;<a href="http://de.wikipedia.org/wiki/Durchblutung">Durchblutung</a>&nbsp;gef&ouml;rdert. Der K&auml;ltereiz l&auml;sst die oberfl&auml;chlichen Blutgef&auml;&szlig;e kontrahieren. Gemeinsam mit der Muskelbewegung f&ouml;rdert dies auch den ven&ouml;sen Blutstrom und beugt&nbsp;<a href="http://de.wikipedia.org/wiki/Krampfader">Krampfadern</a>&nbsp;vor. Abends durchgef&uuml;hrt ist Wassertreten &uuml;brigens eine Hilfestellung zum besseren Einschlafen.</p>',
        Keywords: null,
        Language: 'en',
        MetaDesc:
          'A must-see in South Tyrol that no visitor should miss: 11 Der Nittbach. → Learn more about this great place and get all details on how to arrive. ',
        AuthorTip: null,
        IntroText: '',
        MetaTitle: '11 Der Nittbach • Highlights of South Tyrol',
        SubHeader: null,
        SafetyInfo: null,
        ParkingInfo: null,
        GetThereText: null,
        EquipmentInfo: null,
        AdditionalText: '',
        PublicTransportationInfo: null,
      },
      it: {
        Title: '11 Der Nittbach',
        Header: '',
        BaseText:
          '<p><strong>N i t t &ndash; B a c h &ndash; W a s s e r </strong></p>\r\n<p>&nbsp;</p>\r\n<p><strong>Der Nittbach</strong> selbst, entspringt nicht aus einer eigenen Quelle, sondern bildet sich aus mehreren Rinnsalen, die auf Prader Gemeindegebiet bereits oberhalb der Kalblh&uuml;tte auf ca. 2150 m ihre Urspr&uuml;nge aufweisen. Die Wasser des Nittbaches waren nicht nur f&uuml;r die Prader Flur-Riede, den Nitt-, Standlair- und Tschesswiesen von besonderer Wichtigkeit, sondern sie dienten auch als Trink- und Bew&auml;sserungswasser f&uuml;r den Standlairhof und Teilen des Alt Tschenglser Feldes. Von den Besitzern des Letzteren, war der &bdquo;Gemeinde-Ausrufer&ldquo; von Prad, laut &bdquo;Nittbach-Wasservertrag vom 22. Mai 1510, dazu berechtigt, allj&auml;hrlich am 24. Mai um 13 Uhr am Kirchplatz von Tschengls einen Wasserzins, in Form von Getreide, einzufordern. Zudem legte genanntes Vertragswerk auch ein genaues Wasserbezugsrecht fest. Dessen zugemessene Menge richtete sich nach dem Wasservorkommen und kam allj&auml;hrlich am Mitte Mai-Abend durch die Dorfmeister von Prad und Tschengls an Ort und Stelle zur genauen Aufteilung. Die Wasserzuteilung an die jeweiligen Grundbesitzer nahm hingegen der j&auml;hrlich neu bestellte &bdquo;Waaler&ldquo; vor. Er teilte dem an die Reihe Kommenden den Beginn und die Dauer der Bew&auml;sserungszeit mit. Im Herbst, am Ende der Bew&auml;sserungsperiode, zog der &bdquo;Wasseransager&ldquo; mit Hand-Ziehkarren und Getreidema&szlig; von einem Wasser-Nutznie&szlig;er zum anderen. Denn bei jedem hatte er f&uuml;r seine M&uuml;he, je nach &bdquo;W&auml;sserungsstunden&ldquo;, eine bestimmte Getreidemenge in Empfang zu nehmen. Nach dem Bau der Beregnungs-Anlagen ab den 1970er-Jahren kam dieser alt hergebrachte Brauch zum Erliegen. Der nunmehr so genannte Beregnungswart l&ouml;ste den &bdquo;Waalerdienst&ldquo; ab.</p>\r\n<p><strong>Das &bdquo;Nittbach-Wasser&ldquo;</strong> versorgte stets nicht allein Mensch, Tier und Flur mit seinem kostbaren Nass, sondern es barg in sich dar&uuml;ber hinaus auch noch eine heilende Wirkung. So ist uns &uuml;berliefert, dass fu&szlig;leidende Menschen und Haustiere nach einem Bad in &bdquo;Nittwasser&ldquo; geheilt wurden. Dies bewog gar Einige die eigentliche Quelle zu finden, allein dies gelang aus oben erw&auml;hnten Gr&uuml;nden nicht. In den ersten 1990er-Jahren hat man schlie&szlig;lich unweit des &bdquo;Nittkreuzes&ldquo;, in direkter Weg N&auml;he, eine Art Wassertretanlage errichtet, die seither von G&auml;sten und Einheimischen sehr gerne in Anspruch genommen wird.</p>\r\n<p>Durch das Wassertreten wird der&nbsp;<a href="http://de.wikipedia.org/wiki/Blutkreislauf">Kreislauf</a>&nbsp;angeregt und die arterielle&nbsp;<a href="http://de.wikipedia.org/wiki/Durchblutung">Durchblutung</a>&nbsp;gef&ouml;rdert. Der K&auml;ltereiz l&auml;sst die oberfl&auml;chlichen Blutgef&auml;&szlig;e kontrahieren. Gemeinsam mit der Muskelbewegung f&ouml;rdert dies auch den ven&ouml;sen Blutstrom und beugt&nbsp;<a href="http://de.wikipedia.org/wiki/Krampfader">Krampfadern</a>&nbsp;vor. Abends durchgef&uuml;hrt ist Wassertreten &uuml;brigens eine Hilfestellung zum besseren Einschlafen.</p>',
        Keywords: null,
        Language: 'it',
        MetaDesc:
          'Un "Must See" in Alto Adige: 11 Der Nittbach. Tutte le informazioni su questo posto notevole: • arrivo • descrizione del percorso • contatto • e tanto altro.',
        AuthorTip: null,
        IntroText: '',
        MetaTitle: '11 Der Nittbach • Highlight in Alto Adige',
        SubHeader: null,
        SafetyInfo: null,
        ParkingInfo: null,
        GetThereText: null,
        EquipmentInfo: null,
        AdditionalText: '',
        PublicTransportationInfo: null,
      },
    },
    IsOpen: false,
    Number: null,
    Source: 'LTS',
    Webcam: null,
    AgeFrom: 0,
    AreaIds: ['3037440EA25C4E369CEDA7C5F09B6303'],
    GpsInfo: [
      {
        Gpstype: 'position',
        Altitude: 919.0,
        Latitude: 46.615026,
        Longitude: 10.598475,
        AltitudeUnitofMeasure: 'm',
      },
    ],
    ODHTags: [
      {
        Id: 'kultur sehenswürdigkeiten',
        Self: 'https://api.tourism.testingmachine.eu/v1/ODHTag/kultur%20sehensw%C3%BCrdigkeiten',
      },
      {
        Id: 'sehenswerte plätze',
        Self: 'https://api.tourism.testingmachine.eu/v1/ODHTag/sehenswerte%20pl%C3%A4tze',
      },
      {
        Id: 'historische plätze',
        Self: 'https://api.tourism.testingmachine.eu/v1/ODHTag/historische%20pl%C3%A4tze',
      },
      {
        Id: 'kultur und sehenswürdigkeiten',
        Self: 'https://api.tourism.testingmachine.eu/v1/ODHTag/kultur%20und%20sehensw%C3%BCrdigkeiten',
      },
    ],
    PoiType: '',
    Ratings: null,
    SmgTags: [
      'kultur sehenswürdigkeiten',
      'sehenswerte plätze',
      'historische plätze',
      'kultur und sehenswürdigkeiten',
    ],
    SubType: 'Sehenswerte Plätze',
    CustomId: 'C6F1F5C5B3B39D66A0EF80E5BECE94A4',
    GpsTrack: [],
    OwnerRid: '93FC0A599C214E4585C720C50FE34949',
    DishRates: null,
    FeetClimb: false,
    GpsPoints: {
      position: {
        Gpstype: 'position',
        Altitude: 919.0,
        Latitude: 46.615026,
        Longitude: 10.598475,
        AltitudeUnitofMeasure: 'm',
      },
    },
    Highlight: false,
    OdhActive: false,
    Shortname: '11 Der Nittbach',
    SmgActive: false,
    WayNumber: null,
    Difficulty: null,
    Exposition: null,
    Facilities: null,
    HasRentals: false,
    IsPrepared: false,
    LastChange: '2021-03-10T23:12:08.4130174',
    ChildPoiIds: [],
    FirstImport: '2019-07-19T16:17:03.3699617',
    HasLanguage: ['de', 'it', 'en'],
    IsWithLigth: false,
    LicenseInfo: {
      Author: '',
      License: 'CC0',
      ClosedData: false,
      LicenseHolder: 'LTS',
    },
    PoiProperty: {},
    PoiServices: null,
    RunToValley: false,
    ContactInfos: {
      de: {
        Tax: null,
        Url: 'http://www.prad.info',
        Vat: null,
        City: '',
        Email: 'office@prad.info',
        Address: '',
        LogoUrl: null,
        Surname: '',
        ZipCode: '39026',
        Language: 'de',
        Faxnumber: '',
        Givenname: '',
        NamePrefix: '',
        CompanyName: 'Tourismusverein Prad',
        CountryCode: 'IT',
        CountryName: 'Italy',
        Phonenumber: '+39 0473 616034',
      },
      en: {
        Tax: null,
        Url: 'http://www.prad.info',
        Vat: null,
        City: '',
        Email: 'office@prad.info',
        Address: '',
        LogoUrl: null,
        Surname: '',
        ZipCode: '39026',
        Language: 'en',
        Faxnumber: '',
        Givenname: '',
        NamePrefix: '',
        CompanyName: 'Tourismusverein Prad',
        CountryCode: 'IT',
        CountryName: 'Italy',
        Phonenumber: '+39 0473 616034',
      },
      it: {
        Tax: null,
        Url: 'http://www.prad.info',
        Vat: null,
        City: '',
        Email: 'office@prad.info',
        Address: '',
        LogoUrl: null,
        Surname: '',
        ZipCode: '39026',
        Language: 'it',
        Faxnumber: '',
        Givenname: '',
        NamePrefix: '',
        CompanyName: 'Tourismusverein Prad',
        CountryCode: 'IT',
        CountryName: 'Italy',
        Phonenumber: '+39 0473 616034',
      },
    },
    ImageGallery: [],
    LocationInfo: {
      TvInfo: {
        Id: '93FC0A599C214E4585C720C50FE34949',
        Name: {
          cs: 'Prad am Stilfserjoch/Prato allo Stelvio',
          de: 'Prad am Stilfserjoch',
          en: 'Prato allo Stelvio/Prad am Stilfserjoch',
          fr: 'Prato allo Stelvio/Prad am Stilfserjoch',
          it: 'Prato allo Stelvio',
          nl: 'Prato allo Stelvio/Prad am Stilfserjoch',
          pl: 'Prato allo Stelvio/Prad am Stilfserjoch',
          ru: 'Прато-алло-Стельвио/Prad am Stilfserjoch',
        },
        Self: 'https://api.tourism.testingmachine.eu/v1/TourismAssociation/93FC0A599C214E4585C720C50FE34949',
      },
      AreaInfo: {
        Id: '3037440EA25C4E369CEDA7C5F09B6303',
        Name: {
          cs: 'Prad',
          de: 'Prad',
          en: 'Prad',
          fr: 'Prad',
          it: 'Prad',
          nl: 'Prad',
          pl: 'Prad',
          ru: 'Prad',
        },
        Self: 'https://api.tourism.testingmachine.eu/v1/Area/3037440EA25C4E369CEDA7C5F09B6303',
      },
      RegionInfo: {
        Id: 'D2633A24C24E11D18F1B006097B8970B',
        Name: {
          cs: 'Vinschgau/Val Venosta',
          de: 'Vinschgau',
          en: 'Val Venosta/Vinschgau',
          fr: 'Val Venosta/Vinschgau',
          it: 'Val Venosta',
          nl: 'Val Venosta/Vinschgau',
          pl: 'Val Venosta/Vinschgau',
          ru: 'Валь-Веноста/Vinschgau',
        },
        Self: 'https://api.tourism.testingmachine.eu/v1/Region/D2633A24C24E11D18F1B006097B8970B',
      },
      DistrictInfo: {
        Id: '79CBD84F51C911D18F1400A02427D15E',
        Name: {
          cs: 'Lichtenberg/Montechiaro',
          de: 'Lichtenberg',
          en: 'Montechiaro/Lichtenberg',
          fr: 'Montechiaro/Lichtenberg',
          it: 'Montechiaro',
          nl: 'Montechiaro/Lichtenberg',
          pl: 'Montechiaro/Lichtenberg',
          ru: 'Монтекьяро',
        },
        Self: 'https://api.tourism.testingmachine.eu/v1/District/79CBD84F51C911D18F1400A02427D15E',
      },
      MunicipalityInfo: {
        Id: 'D9300718A9E3418DAB95ABF1E88736DA',
        Name: {
          cs: 'Prad am Stilfser Joch/Prato allo Stelvio',
          de: 'Prad am Stilfser Joch',
          en: 'Prato allo Stelvio/Prad am Stilfser Joch',
          fr: 'Prato allo Stelvio/Prad am Stilfser Joch',
          it: 'Prato allo Stelvio',
          nl: 'Prato allo Stelvio/Prad am Stilfser Joch',
          pl: 'Prato allo Stelvio/Prad am Stilfser Joch',
          ru: 'Прато-алло-Стельвио',
        },
        Self: 'https://api.tourism.testingmachine.eu/v1/Municipality/D9300718A9E3418DAB95ABF1E88736DA',
      },
    },
    MasterPoiIds: null,
    AltitudeSumUp: 0.0,
    BikeTransport: null,
    CategoryCodes: null,
    LiftAvailable: false,
    DistanceLength: 0.0,
    RelatedContent: null,
    SyncUpdateMode: 'Full',
    AltitudeSumDown: 0.0,
    HasFreeEntrance: false,
    OutdooractiveID: '32631674',
    CapacityCeremony: null,
    CopyrightChecked: true,
    DistanceDuration: 0.0,
    AdditionalContact: null,
    OperationSchedule: [
      {
        Stop: '2019-12-01T00:00:00',
        Type: '3',
        Start: '2019-01-01T00:00:00',
        OperationScheduleTime: null,
        OperationscheduleName: {
          de: '',
        },
      },
    ],
    AdditionalPoiInfos: {
      cs: {
        Novelty: '',
        PoiType: '',
        SubType: 'Pozoruhodná místa',
        Language: 'cs',
        MainType: 'Kultura & památky ',
        Categories: ['Pozoruhodná místa'],
      },
      de: {
        Novelty: null,
        PoiType: '',
        SubType: 'Sehenswerte Plätze',
        Language: 'de',
        MainType: 'Kultur & Sehenswürdigkeiten ',
        Categories: ['Sehenswerte Plätze'],
      },
      en: {
        Novelty: null,
        PoiType: '',
        SubType: 'Places to See',
        Language: 'en',
        MainType: 'Culture & Attractions ',
        Categories: ['Places to See'],
      },
      fr: {
        Novelty: '',
        PoiType: '',
        SubType: 'Sites incontournables',
        Language: 'fr',
        MainType: 'Culture & sites touristiques ',
        Categories: ['Sites incontournables'],
      },
      it: {
        Novelty: null,
        PoiType: '',
        SubType: 'Luoghi da vedere',
        Language: 'it',
        MainType: 'Arte e cultura ',
        Categories: ['Luoghi da vedere'],
      },
      nl: {
        Novelty: '',
        PoiType: '',
        SubType: 'Bezienswaardige plaatsen',
        Language: 'nl',
        MainType: 'Cultuur & bezienswaardigheden ',
        Categories: ['Bezienswaardige plaatsen'],
      },
      pl: {
        Novelty: '',
        PoiType: '',
        SubType: 'Niesamowite miejsca',
        Language: 'pl',
        MainType: 'Kultura i atrakcje ',
        Categories: ['Niesamowite miejsca'],
      },
      ru: {
        Novelty: '',
        PoiType: '',
        SubType: 'Интересные места',
        Language: 'ru',
        MainType: 'Культура и достопримечательности ',
        Categories: ['Интересные места'],
      },
    },
    AltitudeDifference: 0.0,
    MaxSeatingCapacity: 0,
    AltitudeLowestPoint: 0.0,
    ODHActivityPoiTypes: [
      {
        Id: 'Kultur Sehenswürdigkeiten',
        Self: 'https://api.tourism.testingmachine.eu/v1/ODHActivityPoiTypes/Kultur%20Sehensw%C3%BCrdigkeiten',
        Type: 'Type',
      },
      {
        Id: 'Sehenswerte Plätze',
        Self: 'https://api.tourism.testingmachine.eu/v1/ODHActivityPoiTypes/Sehenswerte%20Pl%C3%A4tze',
        Type: 'SubType',
      },
    ],
    SyncSourceInterface: 'poidata',
    AltitudeHighestPoint: 0.0,
    TourismorganizationId: '93FC0A599C214E4585C720C50FE34949',
    OutdooractiveElevationID: null,
  },
};
