export { accommodationConfig } from './accommodation/accommodation.config';
export { articleConfig } from './article/article.config';
export { eventShortConfig } from './eventShort/eventShort.config';
export { odhActivityPoiConfig } from './odhActivityPoi/odhActivityPoi.config';
export { odhActivityPoiTypesConfig } from './odhActivityPoiTypes/odhActivityPoiTypes.config';
export { eventConfig } from './event/event.config';
export { eventTopicsConfig } from './eventTopics/eventTopics.config';
export { accommodationTypesConfig } from './accommodationTypes/accommodationTypes.config';
export { webcamInfoConfig } from './webcamInfo/webcamInfo.config';
